### ISSUE TITLE
submitting to cluster not working

### ISSUE THREAD

**Issue by vmkhot** [a-h-b/dadasnake#19]
Hi there, 

I've installed dadasnake on our computing server (slurm) and am trying out the trial run using this command: 

`./dadasnake -c -n "TESTRUN" -r config/config.test.yaml`

the error I get is that there's no "--time" variable set for sbatch.: 

Any thoughts on how to fix it or how to include the time parameter into the submission? 

Your help is greatly appreciated!!

Thanks,

Varada

**Comment by a-h-b** [comment]
Dear Varada - thanks for reaching out. 
I have a few questions to pinpoint the problem:
Have you selected one (which one?) of slurm or slurm_simple in the VARIABLE_CONFIG file for SCHEDULER ? 
Best - A

**Comment by vmkhot** [comment]
Thanks for your reply! 

I selected "slurm" in the VARIABLE_CONFIG file. this is what it looks like

`SNAKEMAKE_VIA_CONDA     true
SNAKEMAKE_EXTRA_ARGUMENTS
LOADING_MODULES
SUBMIT_COMMAND  sbatch
BIND_JOBS_TO_MAIN       false
NODENAME_VAR
SCHEDULER       slurm
MAX_THREADS     20
BIGMEM_CORES    10
BIGMEM_MEM_EACH 6G
NORMAL_MEM_EACH 6G
LOCK_SETTINGS   false`

thanks,

Varada

**Comment by a-h-b** [comment]
Dear Varada -
can you please change the SCHEDULER value from slurm to slurm_simple?
Generally, to change how slurm is called by dadasnake, you can edit the file in the config folder called slurm_simple.config.yaml (config/slurm_simple.config.yaml). 
For example you can try to change line 5 
`  runtime: "-t"`
to 
  runtime: "--time"
I am not completely certain that this will actually help, because I think the -t is a standard abbreviation for --time in slurm.

If it does not help, can you let me know which rule throws this error, i.e. up to which point did it run?
Thanks-
A

**Comment by a-h-b** [comment]
closing for now, I am assuming this is solved
